version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    platform: linux/x86_64 
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./back-end
    platform: linux/x86_64
    restart: 'always'
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS='password'
      - DB_HOST=localhost
      - DB_NAME=NGcash-app
      - DB_PORT=3306
      - NODE_ENV=development
      - EVAL_ALWAYS_RESTORE_DEV_DB=false
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    platform: linux/x86_64 
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
